apiVersion: v1
kind: Service
metadata:
  name: shinosawa-check-service
spec:
  selector:
    app: shinosawa-check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
